### PR TITLE
fix EditRostersForm

### LINKED ISSUE #651: manage_players does not allow moving players to alternate
or rather, moving them does not persist on save. possibly caused by the registration changes? i will investigate.

### PR DESCRIPTION
**Pull request by glbert-does**
fix #651, add a test.

remove expected ratings in some other places. i hope the changes in edit_rosters.js are correct, i don't know all that much about those js files. locally, it seems to work.

### CODE REVIEW

File: heltour/tournament/static/tournament/js/edit_rosters.js [hunk 1]
```diff
@@ -134,35 +134,23 @@ function updateAverage($teams) {
...
-            $team.find('.average-exp-rating').text((totalExp / nExp).toFixed(2));
-        } else {
-            $team.find('.average-exp-rating').text('');
-        }
     }
 }
 
 function updateDisplayedRatings() {
-    attrName = $('#id_rating_type').val() === 'expected' ? 'data-exp-rating' : 'data-rating';
+    attrName = $('#id_rating_type').val() === 'data-rating';
```
Comment (lakinwecker) [inline heltour/tournament/static/tournament/js/edit_rosters.js:153]: This change is not correct. The previous one was checking to see if that rating type form element was set to 'expected'. If it was, it would set the `attrName` variable equal to `'data-exp-rating'. If not, it would set it to `'data-rating`

The new version sets attrName to `false`. becuase `id_rating_type` doesn't exist and  the value will be undefined which does not strictly equal 'data-rating'.

File: heltour/tournament/templates/tournament/admin/edit_rosters.html [hunk 2]
```diff
@@ -55,7 +55,6 @@ <h2>Teams</h2>
                     <th>Board {{ board_number }}</th>
                 {% endfor %}
                 <th>Average</th>
-                <th>Expected</th>
```
Comment (lakinwecker) [inline heltour/tournament/templates/tournament/admin/edit_rosters.html:58]: If you remove this header, don't we have to remove columns below as well?

**Review by lakinwecker — CHANGES_REQUESTED** [review]
The javascript is definitely wrong, although I'm not sure how serious that is.

the template just feels wrong, although I did not verify it.
